### ISSUE TITLE
Avoid duplication of effort

### ISSUE THREAD

**Issue by C0rn3j** [emilmelnikov/a4tech-bloody-backlight-level#1]
Hiya, 
I too forked from maxmati, and I've made some progress since then (and also lots of RE with someone else's help that's not published).

An example - your list of supported mice is useless as the PID is generated from HW ID and detection in the original driver does not work that way.

https://gitlab.com/C0rn3j/a4tech_bloody_p85_driver

Feel free to contact me if you intend to continue this project so we can avoid duplicating our efforts ^^
https://rys.pw/#contact_me

**Comment by emilmelnikov** [comment]
Hi. Actually, I didn't expect someone to stumble upon this repository.
To be honest, I've made this fork because I've wanted to
- play around a little and learn how to work with libusb
- have an utility that runs as a systemd service so that I don't need to run it manually
- make the code and build as simple as possible (e.g. there is no resource management)

To summarize, this repository is just a toy project :)

Also, I didn't invest any time in reverse-engineering the protocol, and thought that maxmati's repository is the only working solution that isn't actively maintained.
Thank you for reaching out! I'm still keeping this project because it works for me now, but I mention your repository in the README so that people won't accidentally take this project as a serious one, and contribute to your project if I have time to spare.

**Comment by C0rn3j** [comment]
Ah, I see.

Yeah, maxmati pretty much gave up on the project due to time constraints (at least that's what I understood from a conversation with him) and is only accepting PRs.

My project is the only 'maintained' one and I work very slowly ^^

Btw I assume you wanted ability to turn the LEDs off/on on demand if you wanted to implement this.

You can already do this by lifting the mouse and pressing the extra button 1, it cycles saved LED animations and one of them is OFF (at least in the defaults).

**Comment by emilmelnikov** [comment]
> Btw I assume you wanted ability to turn the LEDs off/on on demand if you wanted to implement this.

> You can already do this by lifting the mouse and pressing the extra button 1, it cycles saved LED animations and one of them is OFF (at least in the defaults).

My mouse (AL-9) has 3 buttons on the top of the device, and they just change the sensitivity and wheel backlight color (red/green/yellow).

**Comment by C0rn3j** [comment]
>You can already do this **by lifting the mouse** and pressing the extra button 1, it cycles saved LED animations and one of them is OFF (at least in the defaults).

You have to physically lift the mouse up. It should disable every single other button and only have the animation switch one work. Though I'm not sure if the FW for your mouse actually does that, they differ model by model ^^

**Comment by emilmelnikov** [comment]
I've tried this with the the mouse lifted up: it doesn't do anything. I've even tried this with the mouse turned upside down. I guess this feature is indeed not consistent throughout their product line.
